In [72]:
import pandas as pd
data=pd.read_csv('iotdata.csv')

In [73]:
data

Id  Moisture State     Action
0      0      1669   wet  motor off
1      1      1675   wet  motor off
2      2      1680   wet  motor off
3      3      1686   wet  motor off
4      4      1663   wet  motor off
..   ...       ...   ...        ...
145  145      1803   wet  motor off
146  146      1982   wet  motor off
147  147      1574   wet  motor off
148  148      3146   dry   motor on
149  149      1269   wet  motor off

[150 rows x 4 columns]

In [74]:
X=data.iloc[:,1].values

In [75]:
X

array([1669, 1675, 1680, 1686, 1663, 1665, 1104, 1062, 4095, 1023,  959,
        927, 4095,  989,  963,  944, 1127, 1035, 1062, 1130,  990,  915,
       1069, 1021, 1322, 4095, 4095, 4095, 4095, 4095, 4095, 4095, 4095,
       4095, 4095, 3601, 1781,  855,  895, 3162, 3119, 2189, 3071, 1155,
       2163, 1449, 3099, 1059, 1045, 3101, 1940, 1190, 1195, 1200, 1193,
       1215, 1274, 1088, 1142, 1162, 1185, 1185, 1199, 1200, 1205, 1197,
       1198, 1183, 1195, 1207, 1214, 1222, 1220, 1218, 1213, 1189, 1183,
       1205, 3105, 3066, 3070, 1843,  976, 3043, 1709, 1008, 1705, 1207,
       1518, 2032, 1613, 2992, 2986, 2976, 1949,  947, 1251, 2980, 1167,
       3013, 1974, 2234, 1390, 3039, 3024, 3011, 1265, 1327, 1360, 1168,
       1149, 1168, 1179, 1104,  979, 1003, 1473, 1275, 1162, 1058, 1039,
       1413, 1018,  954, 1013, 2933, 1831, 2550, 3067, 1391, 1040, 1274,
       1101, 1072, 1095, 1093, 1141, 1200, 1197, 1093, 1103, 1002, 1518,
       1018, 1090, 1803, 1982, 1574, 3146, 1269], d

In [76]:
X=X.reshape(-1,1)

In [77]:
X

array([[1669],
       [1675],
       [1680],
       [1686],
       [1663],
       [1665],
       [1104],
       [1062],
       [4095],
       [1023],
       [ 959],
       [ 927],
       [4095],
       [ 989],
       [ 963],
       [ 944],
       [1127],
       [1035],
       [1062],
       [1130],
       [ 990],
       [ 915],
       [1069],
       [1021],
       [1322],
       [4095],
       [4095],
       [4095],
       [4095],
       [4095],
       [4095],
       [4095],
       [4095],
       [4095],
       [4095],
       [3601],
       [1781],
       [ 855],
       [ 895],
       [3162],
       [3119],
       [2189],
       [3071],
       [1155],
       [2163],
       [1449],
       [3099],
       [1059],
       [1045],
       [3101],
       [1940],
       [1190],
       [1195],
       [1200],
       [1193],
       [1215],
       [1274],
       [1088],
       [1142],
       [1162],
       [1185],
       [1185],
       [1199],
       [1200],
       [1205],
       [1197],
       [11

In [78]:
Y=data.iloc[:,2].values

In [79]:
Y

array(['wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'dry',
       'wet', 'wet', 'wet', 'dry', 'wet', 'wet', 'wet', 'wet', 'wet',
       'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'dry', 'dry',
       'dry', 'dry', 'dry', 'dry', 'dry', 'dry', 'dry', 'dry', 'dry',
       'wet', 'wet', 'wet', 'dry', 'dry', 'wet', 'dry', 'wet', 'wet',
       'wet', 'dry', 'wet', 'wet', 'dry', 'wet', 'wet', 'wet', 'wet',
       'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'wet',
       'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'wet',
       'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'dry', 'dry', 'dry',
       'wet', 'wet', 'dry', 'wet', 'wet', 'wet', 'wet', 'wet', 'wet',
       'wet', 'dry', 'dry', 'dry', 'wet', 'wet', 'wet', 'dry', 'wet',
       'dry', 'wet', 'wet', 'wet', 'dry', 'dry', 'dry', 'wet', 'wet',
       'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'wet',
       'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'wet', 'dry',
       'wet', 'wet',

In [80]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
Y=le.fit_transform(Y)

In [81]:
Y # wet - 1, dry - 0

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [82]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [83]:
from sklearn.linear_model import LogisticRegression

classifier1=LogisticRegression()
classifier1.fit(X_train,Y_train)

LogisticRegression()

In [84]:
from sklearn.metrics import accuracy_score

Y_pred_classifier1=classifier1.predict(X_test)

print(accuracy_score(Y_test,Y_pred_classifier1))

1.0


In [85]:
import pickle

with open('model.pkl','wb') as model:
    pickle.dump(classifier1,model)

In [86]:
print(classifier1.predict([[1200]]))

[1]
